// import React from 'react'

// import ListRendererJsx from "./ListRendererJsx"

//######################
// Example 3, rendering a list without keys but using Autogenerated Index in map function as the key
// NOTE: You musn't use index as key except if the list fullfils 3 requirements
// 1 - The list doesn't have a unique ID
// 2 - The list is static and won't change so can never be updated
// 3 - The list will never be re-ordered or filtered
// NOTE: Using Index as key on a list that updates will cause serious UI issues
// If your list have no unique key, then it's better you hash a unique key for
// each entry manually or just use a third party library to generate unique key
// for each entry
//######################

function E3IndexAsKeys() {

    //list we want to render
    const people = [
        {
            name: "Oyetunji Ibrahim",
            age: 26,
            expert: "Java"
        },
        {
            name: "Raheem Razaq",
            age: 28,
            expert: "JavaScript"
        },
        {
            name: "Shuaib Mustapha",
            age: 26,
            expert: "PHP"
        },
    ]

    //######################
    //Example 1
    //create the html without using the external ListRendererJsx.js
    let title = "List Rendering - Index as Key (Don't use this unless the list fullfils listed requirements)"
    
    //index is auto-generated in map function and is the second parameter
    const list_html = people.map((person, index) => (
        <p key={index}>{index} - I am {person.name}, age {person.age}, expert in {person.expert}</p>
    ))

    return (
        <div>
            <p>{title}</p>
            {list_html}
        </div>
    )
    //######################

    //######################
    //Example 2
    //create the html using the external ListRendererJsx.js
    // let title = "List Rendering - Table list with keys (Don't use this unless the list fullfils listed requirements)"
    
    // const list_html = people.map((person, index) => <ListRendererJsx key={index} person={person} />)

    // return (
    //     <div>
    //         <p>{title}</p>
    //         {list_html}
    //     </div>
    // )
    //######################

}

export default E3IndexAsKeys
